### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by nncarlson** [szaghi/HASTY#5]
@szaghi, I've long been confused by the licensing scheme for your projects.  You say that it is GPLv3 for FOSS projects and BSD/MIT for closed source projects, but then go on to say to use whatever license one wishes.  Which is it?  If in fact you are willing to license the software under the BSD 2 license to anyone for any purpose, I don't see the point in offering any of the other choices.  It is the most permissive, and as far as I understand compatible with any of the other licenses; e.g., a GPLv3 project can incorporate BSD2 software.

**Comment by szaghi** [comment]
@nncarlson 

You are not alone :smile: 

I have tried to find the best way to tell to the _end-user_: 

> my dear, feel free to do whatever you want with this poor code...

After some web-search I found that:
- as you said, GPLv3 _can_ incorporate BSD2, but often GPL-people are very _skeptical_ with all-other-than GPL; this is the reason why I prefer to maintain _also_ GPL license;
- BSD2 is surely one of the most permissive, thus I prefer to maintain _also_ BSD2 license;
- MIT is very _popular_, BSD3 maybe less, but close to; I would like to trim them out, but I like to be as much as possible _inclusive_.

That said, my cumbersome license-wording simply means: if you want a pure GPLv3 for your FOSS project take it, if you need MIT/BSD2 for integrating into your :dollar: project take them (but also if your is FOSS and based on MIT/BSD2), feel free to select _your preferred license_.

I know this is very cumbersome, moreover it is even worse due to my poor English. If you can amend my unclear wording I will be very happy to correct my sentences, however I prefer to maintain all the current licenses even if they are _overlapping_.

Anyhow thank you for pointing it out.

Cheers.

**Comment by nncarlson** [comment]
In that case I'd suggest dropping the bulleted list that appears to link GPLv3 to FOSS, and the BSD/MIT with closed source/commercial, and simply say something like " ... multi-license system.  You may select a license from the following list that suits your needs: GPL v3, ...."

**Comment by szaghi** [comment]
@nncarlson 

Simple and elegant! You have convinced me :smile: 

Soon I'll modify my _bad addictions_

**Comment by szaghi** [comment]
Dear @nncarlson 

I have re-worded the license statement as following:

HASTY is a Free and Open Source Software (FOSS), it is distributed under a **very permissive** multi-licensing system: selectable licenses are [GPLv3](http://www.gnu.org/licenses/gpl-3.0.html), [BSD2-Clause](http://opensource.org/licenses/BSD-2-Clause), [BSD3-Clause](http://opensource.org/licenses/BSD-3-Clause) and [MIT](http://opensource.org/licenses/MIT), feel free to select the license that best matches your workflow.

> Anyone is interest to use, to develop or to contribute to MORTIF is welcome.

More details can be found on [wiki](https://github.com/szaghi/MORTIF/wiki/Copyrights).

What do you think?

**Comment by nncarlson** [comment]
It's very clear to me now, and shouldn't cause any lawyer angst like I
think the original might have.

**Comment by szaghi** [comment]
@nncarlson Thank you very much for your help, I'll adopt this form hereafter.

Cheers.
